### PR TITLE
Add Tray Icon Context Menu

### PR DESCRIPTION
**Pull request by ifBars**
Adds a context menu to the already available tray icon, requested in issue #597 

This is my first time working with a Razor app, and my first time contributing to this big of a project, therefore I wouldn't doubt that I may have made some mistakes. However, in testing, the context menu works as intended!
image

### CODE REVIEW

**Comment by Blightbuster** [comment]
Hey, thanks for the PR ❤️. Id be fine with merging now. Please have a look at the changes I made and tell me if your ready to merge.

**Comment by Blightbuster** [comment]
Btw. not sure if intended or not but atleast on Win11, the menu does show up when right clicking the tray icon but does not show up when right clicking the taskbar icon.
image
image

**Comment by Blightbuster** [comment]
image
Added the options to the jump list as well 👍

**Comment by ifBars** [comment]
I am on windows 10 so I did not have a way to test windows 11, my apologies. Everything looks great on your end! Thanks

**Comment by Blightbuster** [comment]
Just FYI, if you want to do future PR (which I would ofcause welcome), please do them against the `develop` branch as the current master is kinda outdated.

**Comment by ifBars** [comment]
> Just FYI, if you want to do future PR (which I would ofcause welcome), please do them against the `develop` branch as the current master is kinda outdated.

Will do, thanks :)

**Pull request merged**
