### PR TITLE
Add Trader Price to Tooltip

### PR DESCRIPTION
**Pull request by Ryuichiro**
[image](https://user-images.githubusercontent.com/4333206/147838115-50b32b42-c7a7-4b03-bb7c-d880bd7dca4c.png)
### Changelog
- Added best trader price and avatar to Icon & Name Scan tooltips.

### ToDo
- Add Settings for Tooltips
  - [ ] ShowAvgDayPrice
  - [ ] ShowTraderPrice
  - [ ] ShowQuestHideoutTracker

### CODE REVIEW

**Comment by Ryuichiro** [comment]
Not sure what PRs should be based on or target, so I hope this is correct. ^^
I'm also not invested enough to figure out how to add show/hide settings for content on Razor pages, but if you add something similar for the new Main App page, I may copy&paste stuff to add them to the tooltip.

**Comment by jmromrell** [comment]
It could also be nice to have an option to show the maximum of the market and the trader prices, as sometimes market price goes below vendor prices.

**Comment by Ryuichiro** [comment]
That would be relatively easy to do by writing an `if` statement in the `RatRazor/Pages/Overlay/Index.razor` file, all the data necessary is available there. I like to have both, so you would need to create a separate fork for that.

**Comment by Blightbuster** [comment]
Thanks to your PR, as of [v3.2.1](https://github.com/RatScanner/RatScanner/releases/download/v3.2.1/RatScanner.zip), it now shows the maximum of trader and flea market price. For the moment I decided against displaying both since that wouldnt fit inside a 1x1 scanned item.

**Pull request closed without merging**
