### PR TITLE
Add UI for showing number of required quest items.

### PR DESCRIPTION
**Pull request by DimaVartanian**
This is an awesome tool and thanks for making it! As a newbie I found myself often checking other sites to see if an item was required for any quests or hideout modules so thought I'd take a shot at adding it myself.

I think this isn't 100% done but pretty close. Hoping to get any feedback. I have no experience with .NET and am pretty new to C# as well but tried to follow the standards I saw as best as I could. I used the other pull request that did something similar as a jumping off point but implemented this a bit more efficiently and with more functionality.

This feature relies on my branch of the TarkovWikiScanner to create the 2 new JSON files, which I also have a PR out for with some improvements, which scrapes the wiki to get all quest and hideout item requirements. It's not perfect but is pretty accurate, or at least I haven't found any missing items yet. ([Link](https://github.com/DimaVartanian/TarkovWikiScanner/tree/use_dictionaries)) I was trying to find an accurate external source that didn't require manual work to get this working which is pretty tough. If there is a better source for this info it could be worth switching, but I haven't been able to find one that's totally accurate. 

This adds 3 new optional rows into the main UI which show whether the item is required for any quests, quests with a found in raid requirement or not, and for any hideout upgrades. It will hide any row that has a 0 value and will hide the entire section if it's not required for anything.
scannerSS

Notes
- Didn't add anything to the minimal UI yet. Might be worth adding behind a setting but wanted to see how this is received in general first.
- New data sitting in the data folder right now. Not sure if it makes sense to move this to the API but I obviously couldn't do that
- Depends on lookups for English translation words right now - the wiki doesn't have any uid info. This means this will only work in English until it's addressed. This could be fixed if there's a better stable source for this data or just doing it by hand and keeping it updated. The other pull request had a big array of uid : counts, not sure if that was done by hand. One other source I found is [TarkovTracker](https://github.com/TarkovTracker/tarkovdata) but it doesn't seem fully up to date, and seems to be missing whether FiR is required or not. Open to any thoughts, though.

### CODE REVIEW

**Comment by kokarn** [comment]
Nice PR! This has been requested multiple times so pretty sure it will be welcome.

Either you can use the API we talked about on Discord, or the TarkovTracker dataset.
If the quest type is "find" then it's FIR. That's how it's done internally in the game or it's reflected in both sources.

I'd suggest moving it to the API tho, as that means there doesn't have to be a new version released when quests change.
Here's the query to get the data you need:
```
{
  quests {
    title
    wikiLink
    objectives {
      type
      targetItem {
        id
        name
      }
    number
    }
  }
}
```

**Comment by DimaVartanian** [comment]
Updated to slim this down to only Found in Raid required stuff and use the GraphQL API! After some discussion it seemed like it's not too valuable to see non FiR requirements all the time, at least for now.

Things left
1. Add option to minimal view
2. Polish API/JSON logic - I think there are probably some handy C# and .NET mechanisms I'm just not familiar with so the code I added is pretty tedious - but works without crashing at least.

**Comment by DimaVartanian** [comment]
scannerSS

Updated wording and added an option for the Minimal UI.

**Comment by Blightbuster** [comment]
Hey, thanks for this great PR. I know im pretty late to respond just now but I managed to implement this in cooperation with @thaddeus (the maker of tarkovtracker) for v2.7.0. As far as I can see it pretty much turned out how you started implementing it + your notes but maybe you still have some suggestions for improving it. I will be closing this PR due to it being implemented now. Thanks againg for the effort you put into it ❤️

**Comment by DimaVartanian** [comment]
New update looks good. No worries!

**Pull request closed without merging**
